### ISSUE TITLE
Beta 1.6.0 Bug

### ISSUE THREAD

**Issue by Dephilia** [Dephilia/MisakiAobaBot#53]
1. - [x] In word echo, for url(http://) it should not act.
2. - [x]  It is better that 更新中！>更新中...
3. - [x] 'prob':int(formula('pr',context)), ValueError: invalid literal for int() with base 10: 'prob' 
4. - [x] When savepic, url failed should have log and user return
5. - [ ] Word echo should only run random function once but n+1 times.
6.  - [x] Rule edit admin permit has problem
7. - [x] Quote finder will error while find '杏奈' '蝶芙'
8.  - [x] In any room, Word echo default turn off

**Comment by Dephilia** [comment]
##New function dev
1. Set time to change room title and profile photo
2. Turn on water recorder in each room

**Comment by Dephilia** [comment]
Bug 2 fix

**Comment by TAKE72K** [comment]
Pr #54 to solve 5.
Rand 2 times

**Comment by Dephilia** [comment]
bug6 fixed

**Comment by Dephilia** [comment]
bug 8 fix

**Comment by Dephilia** [comment]
It has been define that the reason of bug.7 is because of the quote is "None" or "error of html".
For example, '(*>△<)' will cause error because '<' is a start symbol of html, and there is no end of it.
The solution is not add this quote or edit the quote so that it can do well.
